language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "boilermaker-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test             # test the code
  - npm run build-client # make the bundle

before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: pommes-de-terre # see README
  api_key:
    secure: "p4363LJhZMRVI/wmdZKP6ydn355mO+XSX96EA0iz2nN2gHxLHnxVzKy+KcdphjfIF4qxvXCKdo1lfaB5BEESqdvGTOubGqrQViDgsFEqkEFVAxJ+DPFsiJs+kWZjF55SDmWKFPBJQyigtyu/gjAhyT2CIEcdej0Lce375SjMMmPSzdQkhE0BGLNm7bUz+boPUPLn0Kub1fSmKDj6h7DuADBqlRqGuvg+B82e+4AVFMluPVYjH8QdrIGxVuLHymWtgqZ/xhz4iJcpKfFlcm1dtfqj3eOlX1iNPBJna2JxjVXAe9ckjGsJYUbTxE3OyGVBWD2jaJomeNzeQmboj6E1n7MTXodkLdfUsFoDi+dXq/m1q3LygkeLGesva2fnLlSQgz4btWdbjve6cZcT9VcRRYiYmhYzVFaeYDxkhtfdZLF4RcbFyDouYok4ngo2gzHdFTGDLrAmtDNP2CPD0kxebFrhXHWUwbeoXYcWB0KjNjcW9D6M77+4pRGJ5KLiBgb7dJJGekYAej2wrQOJAaO1icDCFX3Ot/5qf3vncn4AaFMKZgx9jUXsnUiaWQ4RgOHTlxfw2eMWhfFmNfGzvco5f3Ew9BDURDx7qmET0ncU4RLUn2y2YZDVlR+kQCk/eBrlHYtwomVDYBijnKAr/hUhxy+H5TCegeMllxCLZolFDdY=" # README
